
import type { Metadata } from "next";
import { Noto_Sans_Bengali } from "next/font/google";
import { ReactNode } from "react";
import Navbar from "../components/layout/Navbar";
import { ThemeProvider } from "../components/ui/theme-provider";
import "./globals.css";

const banglaFont = Noto_Sans_Bengali({
  weight: ["400", "500", "600", "700"],
  style: ["normal"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${banglaFont.className} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
